# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0H2k0NinBu-ioJcgHBS5Dyym1ZHrm8o
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#Kütüphaneleri import ettik

sns.set(rc={'figure.figsize':(5,5)}) #figure size için seaborn kütüphanesini kullandık.

df = pd.read_csv("world-happiness-report.csv") #CSV dosyamızı okuduk.

df

df.info()

df['Country name'].value_counts()

df.describe().T #Tablodaki verilerin açıklamalarını yazdırdık.

from os import mkdir
 try:
   mkdir("Plots")
 except:
     pass
 mypath = "Plots" #Veri göresellerimizi saklayacağımız Plots klasörümüzü oluşturduk.

cols = df.select_dtypes(exclude="object") #object verimizi çıkardık, çünkü object üzerinde işlem yapamayız.

from IPython.core.pylabtools import figsize
f,axes = plt.subplots(5,2, figsize=(15,20))
f.tight_layout(pad=8)
f.suptitle('Distrubiton before preprocessig')

x_axis = 0
y_axis = 0

for col in cols:
  sns.histplot(data=df,x=col, kde=True, ax=axes[x_axis, y_axis]) #histogramı oluşturuyoruz.
  axes[x_axis, y_axis].set_xlabel(col.title()) # x düzlemine isim vermek için yazdık.
  axes[x_axis, y_axis].set_ylabel(col.title()) # y düzlemine isim vermek için kullandık.
  axes[x_axis, y_axis].set_title(f"{col.title()} Count") #grafiğin başlığını belirledik.

  if y_axis == 1:
    y_axis = 0
    x_axis +=1
  else:
    y_axis +=1

plt.savefig("Plots/histogram.png")
plt.show()

from IPython.core.pylabtools import figsize
f,axes = plt.subplots(5,2, figsize=(15,20))
f.tight_layout(pad=8)
f.suptitle('Distrubiton before preprocessig')

x_axis = 0
y_axis = 0

for col in cols:
  sns.boxplot(data=df,x=col,ax=axes[x_axis, y_axis]) #histogramı oluşturuyoruz.
  axes[x_axis, y_axis].set_xlabel(col) # x düzlemine isim vermek için yazdık.
  axes[x_axis, y_axis].set_ylabel("Count") # y düzlemine isim vermek için kullandık.
  axes[x_axis, y_axis].set_title(f"{col.title()} Box Count") #grafiğin başlığını belirledik.

  if y_axis == 1:
    y_axis = 0
    x_axis +=1
  else:
    y_axis +=1

plt.savefig("Plots/boxCount.png")
plt.show()

year_group = df.groupby("year").sum()
year_group

year_group['Positive affect'].plot()
plt.savefig("Plots/PositiveAffectPlot.png")

ax1 = sns.barplot(x=year_group.index, y=year_group['Social support'])
ax1.tick_params(axis="x", rotation=90)
plt.savefig("Plots/socialSupport")

import os
from os import listdir, mkdir
from os.path import isfile, join

all_files = os.listdir("Plots/")
report = [f"Plots/{file}"for file in all_files]
print(report) #Plots klasörümüzdeki dosyaların adını yazdırdık.

!pip install FPDF #pdf oluşturma modülünü indiriyoruz.

from fpdf import FPDF

WIDTH =210
HEIGHT = 297 #GENİŞLİK ve YÜKSEKLİK belirledik.

pdf = FPDF()
pdf.set_font("Arial","B",56)

pdf.add_page()
pdf.cell(100, 20, txt='REPORT', align='C')

for report in report:
  pdf.add_page()

  pdf.set_font("Arial", "B",24)
  pdf.cell(100,20,txt='report', align='C')

  pdf.image(report, 5, 30, WIDTH-5)

pdf.output("Countries_Report.pdf","F")

